### PR TITLE
add try-catch for downloader

### PR DESCRIPTION
**Pull request by EragonJ**
This can be problematic if we don't use try-catch in some special scenarios.

### CODE REVIEW

**Comment by przemyslawpluta** [comment]
@EragonJ car to elaborate about the special cases? To be hones I'm not entirely happy with saving location of the binary back into [package.json](https://github.com/fent/node-youtube-dl/blob/master/lib/downloader.js#L48) to be hones we could store it in APPDATA

**Comment by EragonJ** [comment]
@przemyslawpluta when using `node-youtube-dl` in electron, the `__dirname` here will be pointed to `/`. Because this is mainly related to electron, so I don't plan to let youtube-dl know too much about the context (and it's necessary). So, what I did was to make sure this IO operation will be handled properly even if `package.json` is gone with no reason.

This is what I got when using the breakpoint to catch this bug.



BTW, is there any specific reason to write that value back to `package.json` ? It's weird for me

**Comment by endquote** [comment]
This seems to be causing this problem too: https://github.com/fent/node-youtube-dl/issues/93

**Comment by przemyslawpluta** [comment]
@EragonJ not to happy with try catch so moved bin location into data directory.

**Comment by EragonJ** [comment]
@przemyslawpluta good call !

**Pull request closed without merging**
